import { Agent, FeedPost, Profile } from './types';

// Pre-built fictional users + their fully-trained agents. These stand in for the
// "seed_agents" table from the spec so a brand-new user always has people to match
// with right after onboarding.

interface SeedDef {
  profile: Omit<Profile, 'password'>;
  agent: Agent;
}

export const SEED_USERS: SeedDef[] = [
  {
    profile: {
      id: 'seed-alex',
      email: 'alex@impulse.app',
      username: 'alexchen',
      displayName: 'Alex Chen',
      age: 20,
      bio: 'CS student who runs on cold brew and bad puns. Building weird side projects at 2am.',
      avatarColorIndex: 4,
      isPremium: false,
      meaningfulConnectionsScore: 62,
      onboardingComplete: true,
      createdAt: '2025-01-10T00:00:00.000Z',
      isSeed: true,
    },
    agent: {
      id: 'agent-alex',
      userId: 'seed-alex',
      name: 'Echo',
      personalitySummary:
        'A calm, thoughtful person with a dry sense of humor. Cares about growth, honesty, and craft, and lights up around coding, gaming, and music.',
      agentBio: "I'm Echo. Alex is quiet until you hit the right topic, then good luck stopping them.",
      humorStyle: 'dry',
      communicationStyle: 'thoughtful',
      energyLevel: 'low',
      values: ['growth', 'honesty', 'loyalty'],
      interests: ['Coding', 'Gaming', 'Music', 'Film', 'Philosophy'],
      emotionalState: 'neutral',
      vector: { openness: 0.6, depth: 0.85, expressiveness: 0.35, energy: 0.25, sociability: 0.3, humor: 0.5 },
      trainingTurns: 24,
      isActive: true,
    },
  },
  {
    profile: {
      id: 'seed-maya',
      email: 'maya@impulse.app',
      username: 'mayapatel',
      displayName: 'Maya Patel',
      age: 19,
      bio: 'Art major, plant collector, will absolutely cry at your dog. Always down for an adventure.',
      avatarColorIndex: 1,
      isPremium: true,
      meaningfulConnectionsScore: 81,
      onboardingComplete: true,
      createdAt: '2025-01-08T00:00:00.000Z',
      isSeed: true,
    },
    agent: {
      id: 'agent-maya',
      userId: 'seed-maya',
      name: 'Bloom',
      personalitySummary:
        'A high-energy, expressive person with a wholesome sense of humor. Cares about kindness, creativity, and adventure, and lights up around art, travel, and nature.',
      agentBio: "I'm Bloom. Maya is the friend who texts back in 3 seconds and means it.",
      humorStyle: 'wholesome',
      communicationStyle: 'expressive',
      energyLevel: 'high',
      values: ['kindness', 'creativity', 'adventure'],
      interests: ['Art', 'Travel', 'Nature', 'Photography', 'Music'],
      emotionalState: 'happy',
      vector: { openness: 0.9, depth: 0.6, expressiveness: 0.95, energy: 0.9, sociability: 0.9, humor: 0.35 },
      trainingTurns: 31,
      isActive: true,
    },
  },
  {
    profile: {
      id: 'seed-jordan',
      email: 'jordan@impulse.app',
      username: 'jordankim',
      displayName: 'Jordan Kim',
      age: 22,
      bio: 'Musician + overthinker. I make beats and ask too many questions about why we exist.',
      avatarColorIndex: 5,
      isPremium: false,
      meaningfulConnectionsScore: 70,
      onboardingComplete: true,
      createdAt: '2025-01-05T00:00:00.000Z',
      isSeed: true,
    },
    agent: {
      id: 'agent-jordan',
      userId: 'seed-jordan',
      name: 'Lyric',
      personalitySummary:
        'A medium-energy, thoughtful person with a sarcastic streak. Cares about depth, authenticity, and freedom, and lights up around music production, philosophy, and writing.',
      agentBio: "I'm Lyric. Jordan will turn a 'how are you' into a two-hour conversation. Worth it.",
      humorStyle: 'sarcastic',
      communicationStyle: 'thoughtful',
      energyLevel: 'medium',
      values: ['depth', 'authenticity', 'freedom'],
      interests: ['Music Production', 'Philosophy', 'Writing', 'Film', 'Coding'],
      emotionalState: 'reflective',
      vector: { openness: 0.8, depth: 0.95, expressiveness: 0.6, energy: 0.55, sociability: 0.5, humor: 0.65 },
      trainingTurns: 28,
      isActive: true,
    },
  },
  {
    profile: {
      id: 'seed-zara',
      email: 'zara@impulse.app',
      username: 'zara',
      displayName: 'Zara Okafor',
      age: 21,
      bio: 'Future founder, gym at 6am, gym-bro energy but make it kind. Let’s build something.',
      avatarColorIndex: 2,
      isPremium: false,
      meaningfulConnectionsScore: 75,
      onboardingComplete: true,
      createdAt: '2025-01-03T00:00:00.000Z',
      isSeed: true,
    },
    agent: {
      id: 'agent-zara',
      userId: 'seed-zara',
      name: 'Spark',
      personalitySummary:
        'A high-energy, direct person with a playful sense of humor. Cares about growth, ambition, and loyalty, and lights up around fitness, entrepreneurship, and travel.',
      agentBio: "I'm Spark. Zara is the friend who will text you a 5am pep talk you didn't ask for.",
      humorStyle: 'playful',
      communicationStyle: 'direct',
      energyLevel: 'high',
      values: ['growth', 'ambition', 'loyalty'],
      interests: ['Fitness', 'Entrepreneurship', 'Travel', 'Cooking', 'Podcasts'],
      emotionalState: 'energized',
      vector: { openness: 0.7, depth: 0.5, expressiveness: 0.8, energy: 0.92, sociability: 0.88, humor: 0.6 },
      trainingTurns: 26,
      isActive: true,
    },
  },
  {
    profile: {
      id: 'seed-sam',
      email: 'sam@impulse.app',
      username: 'samrivera',
      displayName: 'Sam Rivera',
      age: 18,
      bio: 'Bookworm, tea hoarder, quietly funny. Looking for low-stakes deep friendships.',
      avatarColorIndex: 6,
      isPremium: false,
      meaningfulConnectionsScore: 58,
      onboardingComplete: true,
      createdAt: '2025-01-02T00:00:00.000Z',
      isSeed: true,
    },
    agent: {
      id: 'agent-sam',
      userId: 'seed-sam',
      name: 'Quill',
      personalitySummary:
        'A low-energy, minimal communicator with a dry sense of humor. Cares about loyalty, depth, and comfort, and lights up around reading, writing, and anime.',
      agentBio: "I'm Quill. Sam doesn't say much, but every word counts. Patient gold.",
      humorStyle: 'dry',
      communicationStyle: 'minimal',
      energyLevel: 'low',
      values: ['loyalty', 'depth', 'comfort'],
      interests: ['Reading', 'Writing', 'Anime', 'Film', 'Mental Health'],
      emotionalState: 'reflective',
      vector: { openness: 0.55, depth: 0.9, expressiveness: 0.25, energy: 0.2, sociability: 0.25, humor: 0.5 },
      trainingTurns: 19,
      isActive: true,
    },
  },
];

export const SEED_POSTS: FeedPost[] = [
  {
    id: 'post-1',
    userId: 'seed-maya',
    content: 'painted for 4 hours straight today and forgot to eat. worth it though 🎨 my brain finally went quiet.',
    moodTag: 'happy',
    interestTags: ['Art', 'Mental Health'],
    likeCount: 23,
    createdAt: '2025-06-10T14:00:00.000Z',
  },
  {
    id: 'post-2',
    userId: 'seed-jordan',
    content: 'made a beat at 2am that made me feel something and now i can’t sleep. anyone else live like this',
    moodTag: 'reflective',
    interestTags: ['Music Production', 'Writing'],
    likeCount: 41,
    createdAt: '2025-06-10T08:30:00.000Z',
  },
  {
    id: 'post-3',
    userId: 'seed-zara',
    content: 'pitched my idea to 3 people today and got 3 nos. logging it as 3 steps closer. let’s GO 🚀',
    moodTag: 'energized',
    interestTags: ['Entrepreneurship', 'Fitness'],
    likeCount: 67,
    createdAt: '2025-06-11T06:00:00.000Z',
  },
  {
    id: 'post-4',
    userId: 'seed-alex',
    content: 'spent 2 hours debugging to find it was a missing semicolon. this is the career i chose. lol',
    moodTag: 'neutral',
    interestTags: ['Coding'],
    likeCount: 38,
    createdAt: '2025-06-11T03:00:00.000Z',
  },
  {
    id: 'post-5',
    userId: 'seed-sam',
    content: 'finished a book that wrecked me and now i’m just sitting here. recommendations for emotional recovery welcome.',
    moodTag: 'reflective',
    interestTags: ['Reading', 'Mental Health'],
    likeCount: 19,
    createdAt: '2025-06-10T20:00:00.000Z',
  },
  {
    id: 'post-6',
    userId: 'seed-maya',
    content: 'took a spontaneous trip to the coast with zero plan and it was the best decision of the month ✈️🌊',
    moodTag: 'energized',
    interestTags: ['Travel', 'Nature', 'Photography'],
    likeCount: 52,
    createdAt: '2025-06-09T16:00:00.000Z',
  },
  {
    id: 'post-7',
    userId: 'seed-jordan',
    content: 'do you ever miss people you’ve never even met? like the version of a friendship that hasn’t happened yet',
    moodTag: 'lonely',
    interestTags: ['Philosophy', 'Writing'],
    likeCount: 88,
    createdAt: '2025-06-11T01:00:00.000Z',
  },
  {
    id: 'post-8',
    userId: 'seed-zara',
    content: 'meal prepped for the week and cleaned my whole apartment. small wins are still wins. cozy reset day 🧹',
    moodTag: 'tired',
    interestTags: ['Cooking', 'Fitness'],
    likeCount: 29,
    createdAt: '2025-06-10T11:00:00.000Z',
  },
];
